In [10]:
import numpy as np


In [11]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [12]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b) 

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
#get dimentions
a.ndim

1

In [14]:
#get shape
b.shape

(2, 3)

In [15]:
#get type
a.dtype

dtype('int32')

In [16]:
#get size
a.itemsize

4

In [17]:
#get total size
a.nbytes


12

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#get specific element[r,c]
a[1,4]


np.int64(12)

In [20]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
#get specific column
a[:,2]

array([ 3, 10])

In [22]:
#getting little more fancy [start index :end index:step size]
a[0,0:6:2]


array([1, 3, 5])

In [23]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
a[:,2]=5
print(a)

a[:,3]=[1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  1  5  6  7]
 [ 8  9  5  2 12 20 14]]


In [25]:
#3d example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
#get specific element(work outside in)
b[0,0,:]

array([1, 2])

In [27]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [28]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [29]:
#all 0s matrix

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [30]:
#All 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [31]:
#any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [33]:
#all other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
#random decimal numbers
np.random.rand(4,2)

array([[0.25119357, 0.92450253],
       [0.9725787 , 0.82641484],
       [0.98594085, 0.49320362],
       [0.07784787, 0.37317477]])

In [47]:
#random integer values
np.random.randint(7,size=(3,3))

array([[3, 5, 6],
       [5, 3, 6],
       [1, 2, 2]], dtype=int32)

In [50]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
#repeat an array 
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [64]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print (output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [69]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


In [102]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [103]:
a+2


array([3, 4, 5, 6])

In [104]:
a-2

array([-1,  0,  1,  2])

In [105]:
a*2

array([2, 4, 6, 8])

In [106]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [107]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [111]:
a**3

array([ 1,  8, 27, 64])

In [112]:
#take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [113]:
######linear algebra




In [117]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
b

[[1. 1. 1.]
 [1. 1. 1.]]


array([[2, 2],
       [2, 2],
       [2, 2]])

In [118]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [120]:
c=np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [121]:
######statistics

In [123]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
np.min(stats)

np.int64(1)

In [125]:
np.max(stats)

np.int64(6)

In [126]:
np.max(stats,axis=1)

array([3, 6])

In [127]:
np.sum(stats)

np.int64(21)

In [128]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [129]:
#####reorganizing arrays

In [130]:
before=np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [131]:
before.shape

(2, 4)

In [134]:
after=before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [136]:
#vertically stacking vectors/matrices
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [137]:
#HORIZONTAL STACK
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack([h1,h2])



array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [138]:
#load data from file
np.genfromtxt('data.txt',delimiter=',')

FileNotFoundError: data.txt not found.